###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://www.project-piper.io/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###



### General project setup
general:
  buildTool: 'mta'
  #inferBuildTool: true

### Step-specific configuration
steps:
  mavenExecute:
    dockerImage: devxci/mbtci:1.0.14

  artifactPrepareVersion:
    versioningType: cloud_noTag

  npmExecuteLint:
  failOnError: true

  cloudFoundryDeploy:
    mtaDeployParameters: '-f --version-rule ALL'
  tmsUpload:
    nodeName: "QAS"
    credentialsId: "tms-instance-sk" 

### Stage-specific configuration
stages:
  Build:
    mavenExecuteStaticCodeCheck: false
    npmExecuteLint: true

Additional Unit Tests:
  npmExecuteScripts: false
  karmaExecuteTests: false

  #'Confirm':
  #  manualConfirmation: false

#  Integration:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

Acceptance:
  cloudFoundryDeploy: false
  cfApiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
  cfOrg: 'a2399349trial'
  cfSpace: 'dev'
  cfAppName: 'app'
  cfCredentialsId: 'deploy-to-cf'
  uiVeri5ExecuteTests: false

Release:
  cloudFoundryDeploy: false
  cfApiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
  cfOrg: 'a2399349trial'
  cfSpace: 'dev'
  cfAppName: 'app'
  cfCredentialsId: 'deploy-to-cf'
  tmsUpload: true



  #  cfTargets:
  #   - org: 'a2399349trial'
  #     space: 'dev'
  #    apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
  #   appName: 'app'
  #      manifest: 'manifest.yml'
  #     credentialsId: 'hussaini-ali@outlook.com'
